rules:
  - "§e"
  - "§e§l▬▬▬▬▬▬▬▬▬▬▬▬ §6§lServer Rules §e§l▬▬▬▬▬▬▬▬▬▬▬▬"
  - "§7➤ §b1. §fRespect all players. Harassment or abuse is not tolerated."
  - "§7➤ §b2. §fNo griefing or stealing. Play fair."
  - "§7➤ §b3. §fNo hacking or cheating. Use only approved mods."
  - "§7➤ §b4. §fNo spamming or advertising in chat."
  - "§7➤ §b5. §fKeep the chat appropriate for all ages."
  - "§e§l▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
  - "§e"
